import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>h1 </h1>
        <h2>Main</h2>
      </main>
      <footer>
        <h2>Footer</h2>
      </footer>
    </div>
  );
};

export default Home;
