import type { NextPage } from 'next';
import Container from '../shared/components/container/Container';
import Head from 'next/head';

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <h3>h3</h3>
      </nav>
      <Container>
        <p>1</p>
        <p>1</p>
        <p>1</p>
        <main>
          <h1>Este es un título h1 </h1>
          <h2>Este es un título h2</h2>
          <h3>Este es un subtítulo h3</h3>
          <p>
            Lorem ipsum dolor sit amet <strong>consectetur</strong> adipisicing elit. Sint
            enim impedit, voluptate voluptas consequatur labore quibusdam sit doloribus
            omnis dolorem nesciunt <strong>delectus</strong> odio natus, inventore
            deleniti tempora. Eum, exercitationem ipsam!
          </p>
        </main>
        <div className="color-test">
          <h3>h3</h3>
        </div>
        <footer>
          <h2>h2</h2>
        </footer>
      </Container>
    </div>
  );
};

export default HomePage;
