import type { NextPage } from 'next';
import Container from '../shared/components/container/Container';
import Head from 'next/head';
import Navbar from '../shared/components/navbar/Navbar';

import { FaMeteor, FaBars } from 'react-icons/fa';

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar>
        <span className="font-size-lg">
          DG
          <FaMeteor className="text-fourth font-size-sm" />
          PORTFOLIO
        </span>
        <input placeholder="Search ..." />
        <FaBars />
      </Navbar>
      <Container>
        <header>
          <h1 className="m-40">
            <span className="font-size-2xl">My name is </span>
            <span className="font-size-4xl">Diego Grassino</span>
          </h1>
          <h2>
            <span className="font-size-xl">and i'm a Front End Developer.</span>
          </h2>
        </header>
        <main>
          <h3>About Me</h3>
          <h3>Portfolio</h3>
        </main>
        <footer>
          <h2>Footer</h2>
        </footer>
      </Container>
    </div>
  );
};

export default HomePage;
